<style>
    afterpay-placement {
        white-space: break-spaces;
        display: block;
        clear: both;
    }
</style>
<script
        src="<?php echo $SDK_URL;?>"
        data-min="<?php echo $CLEARPAY_MIN_AMOUNT;?>"
        data-max="<?php echo $CLEARPAY_MAX_AMOUNT;?>"
        async>
</script>
<script type="text/javascript">
    window.onload = function(e)
    {
        var selectors = "<?php echo $PRICE_SELECTOR;?>";
        var arrSelectors = selectors.split('|');
        var selector = arrSelectors[0];
        for (var i = 0; i < arrSelectors.length; i++) {
            if (document.querySelectorAll(arrSelectors[i]).length > 0) {
                selector = arrSelectors[i];
                break;
            }
        }

        Afterpay.createPlacements({
            targetSelector: "<?php echo $PRICE_SELECTOR_CONTAINER;?>",
            attributes: {
                locale:"<?php echo $ISO_COUNTRY_CODE;?>",
                currency:"<?php echo $CURRENCY;?>",
                amountSelector: selector,
                id: "ClearpaySimulator"
            }
        });
    };
</script>