<?php
/**
 * @var Mage_Payment_Block_Form $this
 */

$logoUrl =$this->getSkinUrl('images/clearpay/logo.png');
$magentoVersion = str_replace('.', '-', substr(Mage::getVersion(), 0, 3));
?>
<style>
    .clearpay-payment-method {
        clear: both;
    }
    .clearpay-payment-method #logo {
        float: right;
        width: 75px;
    }
    .magento-1-6 {
        display: inline-block;
    }
    .magento-1-6 #logo {
        float: none;
    }
    input#p_method_clearpay {
        height: 35px;
    }
</style>
<script>
    var element = document.getElementById("afterpay-placement-widget");
    element.setAttribute("data-amount", window.quoteBaseGrandTotal);
</script>
<div class="clearpay-payment-method magento-<?php echo $magentoVersion; ?>">
    <afterpay-placement id="afterpay-placement-widget"
            data-size="sm"
            data-show-interest-free="false"
            data-amount="<?php echo $TOTAL_AMOUNT;?>"
            data-locale="<?php echo $ISO_COUNTRY_CODE;?>"
            data-currency="<?php echo $CURRENCY;?>">
    </afterpay-placement>
</div>
