<?php
/**
 * @var Mage_Payment_Block_Form $this
 */

$logoUrl =$this->getSkinUrl('images/clearpay/logo.png');
$magentoVersion = str_replace('.', '-', substr(Mage::getVersion(), 0, 3));
?>
<style>
    .clearpay-payment-method {
        clear: both;
    }
    .clearpay-payment-method #logo {
        float: right;
        width: 75px;
    }
    .magento-1-6 {
        display: inline-block;
    }
    .magento-1-6 #logo {
        float: none;
    }
</style>
<div class="clearpay-payment-method magento-<?php echo $magentoVersion; ?>">
    <?php echo $TITLE; ?><img id="logo" src="<?php echo $logoUrl ?>"/>
</div>
