<div class="clearpay_cart_info" style="display: none">
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function(event) {
            var div1 = document.querySelectorAll("<?php echo $POSITION_SELECTOR; ?>");
            var div2 = document.getElementsByClassName("clearpay_cart_info");

            if (div1.length > 0 && div1.length > 0) {
                div1 = div1[0];
                div2 = div2[0];
                div1.after(div2);
                div2.style.setProperty('display', 'block');
            }
        })
    </script>
    <style>
        .payment-method-note.clearpay-cart-note {
            padding: 20px 0 10px 0;
            text-align: left;
        }
        .payment-method-note.clearpay-cart-note.ps-1-6{
            float: right;
            width: 350px;
        }
        .clearpay-cart-note span {
            font-size: 0.85rem;
        }
        .clearpay-cart-note.ps-1-6 span {
            font-size: 1.20rem;
        }
        .clearpay-price-text {
            font-weight: bold;
        }
        .clearpay-more-info {
            text-align: right;
            font-size: 0.85rem;
        }
        .clearpay-cart-note.ps-1-6 .clearpay-more-info {
            font-size: 1.20rem;
        }

    </style>
    <div class="payment-method-note clearpay-cart-note" style="">
        <afterpay-placement
                data-locale="<?php echo $ISO_COUNTRY_CODE;?>"
                data-currency="<?php echo $CURRENCY;?>"
                data-amount="<?php echo $AMOUNT;?>"
                data-size="sm">
        </afterpay-placement>
        <span><?php echo $DESCRIPTION_TEXT_ONE; ?></span>
        <br><br>
        <span><?php echo $DESCRIPTION_TEXT_TWO; ?></span>
        <br>
    </div>
</div>